name: API-HealthCheck

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  httpRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check HTTP status
        id: check
        run: echo "status=$(curl -o /dev/null -s -w %{http_code} https://ec2-43-200-158-138.ap-northeast-2.compute.amazonaws.com/join/exist?username=admin1234)">>$GITHUB_OUTPUT
      
      - name: Check
        run: echo "${{ steps.check.outputs.status }}"

      - name: Error Slack notification
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        if: steps.check.outputs.status == '200'
        with:
          channel-id: 'C05HYST2DQX'
          payload: |
            {
              "text": "GitHub Action build result:",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
