name: Java CI with Gradle

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
          - name: Checkout
          - uses: actions/checkout@v3
          
          - name: Setup JDK 17
            uses: actions/setup-java@v3
            with:
              java-version: '17'
              distribution: 'corretto'
            
          - name: Build with Gradle
            run: ./gradlew build
            working-directory: ./backend
