name: Check Naver HTTP Status

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  httpRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check HTTP status
        id: check
        run: echo "::set-output name=status::$(curl -o /dev/null -s -w "%{http_code}\n" https://ec2-43-200-158-138.ap-northeast-2.compute.amazonaws.com/join/exist?username=admin1234)"
      
      - name: Notify if status is not 200
        uses: act10ns/slack@v1
        with:
          status: ${{ steps.check.outputs.status == '200' && 'success' || 'failure' }}
          steps: ${{ toJson(steps) }}
        if: ${{ steps.check.outputs.status != '200' }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
