name: API-HealthCheck

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  httpRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check HTTP status
        id: check
        run: echo "status=$(curl -o /dev/null -s -w \"%{http_code}\" https://ec2-43-200-158-138.ap-northeast-2.compute.amazonaws.com/join/exist?username=admin1234)">>$GITHUB_OUTPUT
      - name: Check
        run: echo "${{ steps.check.outputs.status }}"
      
      - name: Normal Slack notification
        if: steps.check.outputs.status == '200'
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          token: ${{ secrets.SLACK_WEBHOOK_URL }} # replace this with your slack token

      - name: Error Slack notification
        if: steps.check.outputs.status != '200'
        uses: act10ns/slack@v1
        with:
          status: failure
          steps: ${{ toJson(steps) }}
          token: ${{ secrets.SLACK_WEBHOOK_URL }} # replace this with your slack token
