name: API-HealthCheck

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  httpRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check HTTP status
        id: check
        run: echo "status=$(curl -o /dev/null -s -w %{http_code} https://ec2-43-200-158-138.ap-northeast-2.compute.amazonaws.com/join/exist?username=admin1234)">>$GITHUB_OUTPUT
      - name: Check
        run: echo "${{ steps.check.outputs.status }}"

      - name: Error Slack notification 
        if: steps.check.outputs.status == '200'
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "서버 상태",
              "attachments": [
                {
                  "pretext": "<!channel>",
                  "color": "#dc3545",
                  "fields": [
                    {
                      "title": "서버 상태",
                      "short": false,
                      "value": "서버가 다운되었습니다."
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
