# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  workflow_dispatch:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: kill 8080 port if exist
        run: |
          if sudo lsof -i :8080; then
            echo "Port 8080 is already in use. Killing the process..."
            sudo lsof -i :8080 | awk 'NR!=1 {print $2}' | sudo xargs kill -9
          fi
      - name: gradle bootjar
        working-directory: ./backend
        run: |
          chmod +x ./gradlew
          ./gradlew bootjar
          nohup java -jar ./build/libs/DigginRoom-0.0.1-SNAPSHOT.jar &
