name: Development CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'  
    
    - name: Create config.properties
      run: |
        cd android && echo "server.url=\"https://ec2-43-200-158-138.ap-northeast-2.compute.amazonaws.com/\"" > config.properties

    - name: Init with Gradle
      working-directory: ./android
      run: ./android/gradlew init
      
    - name: Build with Gradle
      run: ./android/gradlew build
      
    - name: Build APK
      working-directory: ./android
      run: ./gradlew assembleDebug --stacktrace

    - name: Slack Upload APK 
      uses: MeilCli/slack-upload-file@v1.0.0 
      with: 
        slack_token: ${{ secrets.SLACK_READ_WRITE_TOKEN }} 
        channels: ${{ secrets.SLACK_CHANNEL_DEPOLY }}
        initial_comment: 'APK File Upload' 
        file_type: 'apk' 
        file_name: 'app-debug.apk' 
        file_path: './android/app/build/outputs/apk/debug/app-debug.apk'
         
